version: '3'

networks:
  default:

services:
  first-app:
    container_name: first-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file: ./.env
    depends_on:
      - mysql-db
      - redis
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306
      MYSQL_USER: marco
      MYSQL_PASSWORD: 1al2356M@rn
      MYSQL_DATABASE: first_app
      REDIS_HOST: redis
      REDIS_PORT: 6379

  mysql-db:
    # NOTE: Uncomment the line below if you are using Mac with m1/m2 chip
    # platform: linux/x86_64
    container_name:  mysql-db
    image: mysql:latest
    command: --bind-address=0.0.0.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: 1al2356M@rn
      MYSQL_DATABASE: first_app
      MYSQL_USER: marco
      MYSQL_PASSWORD: 1al2356M@rn
    ports:
      - "3306:3306"
    stdin_open: true
    tty: true
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default

  redis-db:
    container_name: redis-db
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mysql-data:
