version: '3'

services:
  first-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: marco
      MYSQL_PASSWORD: 1al2356M@rn
      MYSQL_DATABASE: first_app
      REDIS_HOST: redis
      REDIS_PORT: 6379

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1al2356M@rn
      MYSQL_DATABASE: first_app
      MYSQL_USER: marco
      MYSQL_PASSWORD: 1al2356M@rn
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

volumes:
  mysql-data:
